### PR TITLE
Remove dependency on errors package

### PR DESCRIPTION
**Pull request by juanpaucar**
@mightybyte could you check it please? it's correctly being built and tests are passing. I loosed the constraint so this could work with stackage nighty that already uses ghc 7.10.1

cc/ @jpvillaisaza

### CODE REVIEW

**Comment by mightybyte** [comment]
errors-2.0 is a major breaking change.  This will need a closer investigation before merging and I won't be able to get to it right away.  In the meantime I would suggest not using stackage as it locks you down to the new errors version.

**Comment by juanpaucar** [comment]
Hi, i checked all the places that snap-extras uses Control.Error... the only function that can only be used from errors library is `Control.Error.Util (note)`and this function hasn't changed the signature from [1.4.7](http://hackage.haskell.org/package/errors-1.4.7/docs/Control-Error-Util.html#v:note) to [2.0.0](http://hackage.haskell.org/package/errors-2.0.0/docs/Control-Error-Util.html#v:note) .
The other functions and types that are used from `Control.Error` are: `isJust`, `fromMaybe`, `runMaybeT`,  `readMay`, `fromMaybe`. These all belong to other modules being re-exported from `Control.Error` so i don't think that it is a major breaking change.

PS: Only 3 files use Control.Error, and only one actually uses a function that can only be found on the errors package
- src/Snap/Extras/FormUtils.hs
- src/Snap/Extras/PollStatus.hs
- src/Snap/Extras/Tabs.hs

**Comment by mightybyte** [comment]
@juanpaucar Thanks for the good research.  Given what you found I think the right solution here is to remove out dependency on the errors package completely and just paste in the code for the note function.  If you want to put together a pull request for this, that would probably speed things along.

**Comment by juanpaucar** [comment]
@mightybyte sure thing

**Comment by juanpaucar** [comment]
@mightybyte could you take a look, please? Is there something that should be changed?

**Comment by mightybyte** [comment]
Looks good to me.  Thanks!

**Pull request merged**
